### ISSUE TITLE
Creación y testing de metodos UnitTest

### ISSUE THREAD

**Issue by Lumexio** [Lumexio/Pocket-Bar#36]
- [ ] En el Api, crear los metodos unit test
- [ ] Ver manual mente y forzar errores o entradas no permitidas y validar las mismas

**Comment by Lumexio** [comment]
- [ ] asdas

**Comment by FaridCG343** [comment]
- [ ] Tickets
- [ ] Artículos
- [ ] Categorías
- [ ] Marcas
- [ ] Proveedores
- [ ] Tipos
- [ ] Usuarios
- [ ] Workshift
