### ISSUE TITLE
Datos erroneos al momento de pagar

### ISSUE THREAD

**Issue by Jinxtrot** [Lumexio/Pocket-Bar#52]
Una vez ingresado en la cuenta de _**cajero**_ y se desea pagar una orden con los dos metodos de pago, en este caso, tanto con efectivo y tarjeta. Estos son los datos que introduje para pagar: 
<img width="591" alt="imagen" src="https://user-images.githubusercontent.com/122041652/233865455-be09e103-b6da-4501-a333-98db2df95b95.png">
Y me arroja esto al momento de pagar: 
<img width="591" alt="imagen" src="https://user-images.githubusercontent.com/122041652/233865472-b3143bac-0f77-49bf-a2d2-04bb46048b13.png">
Siendo que no estan dando bien los resultados de pago tanto para el ingresado como para el cambio.

**Comment by Lumexio** [comment]
![imagen](https://github.com/Lumexio/Pocket-Bar/assets/55640491/a3972273-7df3-4814-96fe-0f013f351d48)
