### ISSUE TITLE
Colleccion de insomnia

### ISSUE THREAD

**Issue by FaridCG343** [Lumexio/Pocket-Bar#69]
Este issue se creó para subir la colleccion de insomnia donde están los request

**Comment by Lumexio** [comment]
<details><summary>Details</summary>
<p>

Para lunes 13 de Agosto

</p>
</details>

**Comment by Lumexio** [comment]
No olvides subir tus cambios para hoy y asi porder empezar a ver que cambios hiciste para adaptarlos al frontend
