### ISSUE TITLE
Devolver password generado en nueva DB multitenant

### ISSUE THREAD

**Issue by Lumexio** [Lumexio/Pocket-Bar#74]
Cuando se crea una DB nueva en multitenansy generamos una password temporal que el usuario debe resetear de inmediato.
Esto no significa que el usuario no va a poder logearse con esa clave.
Podrá hacerlo pero, en el response del login se devolverá un parametro booleano  que si esta en "false" desde el cliente solo se mostrara una opción para resetear contraseña.

**Comment by FaridCG343** [comment]
En el primer inicio de sesion se tiene que redigir al usuario a la vista para cambiar la contraseña solo si en la respuesta del login el parametro "cambiar_password" es true

**Comment by Lumexio** [comment]
Cuando se crea el _tenant_, devuelve en el response un password del usuario emisor
esto debe ser resuelto a la brevedad.
@FaridCG343 requiere validar que haya una suscripción activa al momento de crear una **sucursal|_tenant_**

### Nota:
Esto es parte de la sesión de trabajo del 25/02/2024
