### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by FaridCG343** [Lumexio/Pocket-Bar#81]
Para la administración de suscripciones se tienen que implementar los webhooks para saber si los pagos funcionan o fallan, de igual manera si deciden cacelarla

**Comment by Lumexio** [comment]
También se debe cambiar el DBMS en el api de MariaDB a PostgreSQL.
@FaridCG343 

Nota: 
Esto es parte de la sesión de trabajo del 11/02/2024

**Comment by Lumexio** [comment]
Para que este issue este completamente finalizado @Lumexio tiene que terminar #76 #77
